(function(){
const ABX_STORE_DEFAULT={mode:'home',caseIndex:{rounds:0,loadout:0,culture:0,boss:0},score:0,total:0,consults:0,weakness:{},reviewQueue:[],algorithmStep:0,lastResult:null,consultCase:{}};
function abxData(){return window.MSK_DATA.antibiotic_command;}
function abxState(){state.antibioticCommand={...ABX_STORE_DEFAULT,...(state.antibioticCommand||{})};state.antibioticCommand.caseIndex={...ABX_STORE_DEFAULT.caseIndex,...(state.antibioticCommand.caseIndex||{})};state.antibioticCommand.weakness=state.antibioticCommand.weakness||{};state.antibioticCommand.reviewQueue=state.antibioticCommand.reviewQueue||[];state.antibioticCommand.consultCase=state.antibioticCommand.consultCase||{};return state.antibioticCommand;}
function abxById(id){return abxData().antibiotics.find(a=>a.id===id)||{id,name:id,coverage:[],route:''};}
function abxNames(ids){return (ids||[]).map(id=>abxById(id).name).join(' + ')||'No antibiotics';}
function abxCaseFacts(c){return `<div class="abx-facts"><div><b>Age</b><span>${esc(c.presentation.age)}</span></div><div><b>Chief complaint</b><span>${rich(c.presentation.chief)}</span></div><div><b>Vitals</b><span>${rich(c.presentation.vitals)}</span></div><div><b>Exam</b><span>${rich(c.presentation.exam)}</span></div><div><b>Risk factors</b><span>${rich(c.presentation.risk)}</span></div><div><b>Labs/imaging</b><span>${rich(c.presentation.labs)}; ${rich(c.presentation.imaging)}</span></div></div>`}
function abxGramTag(label){const l=String(label||'').toLowerCase();let cls=l.includes('positive')?'pos':l.includes('negative')?'neg':l.includes('mixed')||l.includes('anaer')?'mixed':'none';return `<span class="abx-gram ${cls}">${esc(label||'none seen')}</span>`}
function abxPathTag(classification){const cls=classification==='Joint infection'?'joint':classification==='Bone infection'?'bone':classification.includes('Mimic')?'mimic':'special';return `<span class="abx-path ${cls}">${esc(classification)}</span>`}
function abxAntibioticChip(a,role){return `<button class="abx-chip antibiotic" draggable="true" data-role="${esc(role)}" data-id="${esc(a.id)}" ondragstart="abxDragStart(event)" onclick="abxToggleChip(this)"><b>${esc(a.name)}</b><span>${esc(a.route)}</span><small>${esc((a.coverage||[]).join(' | '))}</small></button>`}
function abxChoiceButton(group,value){return `<button class="abx-option" data-group="${esc(group)}" data-value="${esc(value)}" onclick="abxChooseOne(this)">${rich(value)}</button>`}
function abxSelected(group){return document.querySelector(`.abx-option.selected[data-group="${CSS.escape(group)}"]`)?.dataset.value||''}
function abxSelectedIds(role){return [...document.querySelectorAll(`.abx-chip.selected[data-role="${CSS.escape(role)}"]`)].map(x=>x.dataset.id)}
function abxSetEqual(selected,correct){const a=[...(selected||[])].sort().join('|'),b=[...(correct||[])].sort().join('|');return a===b}
function abxMatches(selected,correct,alternatives){return abxSetEqual(selected,correct)||(alternatives||[]).some(alt=>abxSetEqual(selected,alt))}
function abxModeLabel(mode){return {rounds:'Case Rounds',loadout:'Antibiotic Loadout',culture:'Culture Callback',boss:'Final Boss'}[mode]||'Case Rounds'}
function abxDeck(mode){const cases=abxData().cases;if(mode==='loadout')return cases.filter(c=>c.empiric.length||c.classification.includes('Mimic'));if(mode==='culture')return cases.filter(c=>c.culture);if(mode==='boss')return cases.filter(c=>c.difficulty>=2).slice(0,12);return cases}
function abxCurrentCase(mode,d=0){const st=abxState(),deck=abxDeck(mode);let idx=st.caseIndex[mode]||0;if(d){idx=(idx+d+deck.length)%deck.length;st.caseIndex[mode]=idx;save()}return deck[idx]}
function abxWeaknessRows(){const entries=Object.entries(abxState().weakness).sort((a,b)=>b[1]-a[1]);if(!entries.length)return '<p class="small">No weakness tags yet. Missed concepts will appear here and re-enter future cases.</p>';return `<div class="abx-weak-grid">${entries.map(([k,v])=>`<span class="source-chip">${esc(k.replaceAll('_',' '))}: ${v}</span>`).join('')}</div>`}
function abxAlgorithmCard(compact=false){return `<article class="card abx-algorithm"><div class="arena-top"><div><span class="tag">Always available</span><h3>Algorithm Card</h3></div><button onclick="abxDrawMode('algorithm')">Train algorithm</button></div><div class="abx-algo-grid"><div class="abx-algo-path joint"><h4>Joint pathway</h4><p><b>Septic arthritis</b>: aspirate if no major delay, start empiric antibiotics, usually ${abxChipText('vancomycin')}. Young child/Kingella: ${abxChipText('vancomycin')} + ${abxChipText('ceftriaxone')}. IVDU: add ${abxChipText('cefepime')} or ${abxChipText('piperacillin_tazobactam')}.</p><p><b>Lyme arthritis</b>: ${abxChipText('doxycycline')} or ${abxChipText('amoxicillin')} in young children. <b>Transient synovitis</b>: no antibiotics.</p></div><div class="abx-algo-path bone"><h4>Bone pathway</h4><p><b>Osteomyelitis</b>: blood cultures, MRI, bone/abscess culture when possible. Start Staph/MRSA coverage with ${abxChipText('vancomycin')}; broaden for IVDU/open fracture/hardware.</p><p>Open fracture/direct inoculation: ${abxChipText('vancomycin')} + ${abxChipText('piperacillin_tazobactam')} or ${abxChipText('vancomycin')} + ${abxChipText('cefepime')} + ${abxChipText('metronidazole')}.</p></div></div>${compact?'':'<p class="small"><b>Durations:</b> septic arthritis 3 to 4 weeks; acute osteomyelitis 4 to 6 weeks minimum; chronic osteomyelitis often >=6 months or suppressive therapy.</p>'}</article>`}
function abxChipText(id){return `<span class="abx-inline-chip">${esc(abxById(id).name)}</span>`}
function renderAntibioticCommand(){const m=window.MSK_DATA.modules.find(x=>x.id==='antibiotic');renderShell('antibiotic',m.title,m.desc,m.sources,`<div id="abxBody"></div>`);abxDrawHome()}
function abxDrawHome(){const d=abxData(),st=abxState();const body=document.getElementById('abxBody');if(!body)return;body.innerHTML=`<section class="abx-hero card"><div><span class="tag source">MSK Infection Command</span><h2>${esc(d.title)}</h2><p>Classify the syndrome, choose the diagnostic action, build a yellow-card antibiotic loadout, interpret cultures, narrow therapy, and choose duration. Broad coverage helps only when the risk profile justifies it.</p><div class="abx-scorebar"><span><b>${st.score}</b> points</span><span><b>${st.total}</b> possible</span><span><b>${Object.keys(st.weakness).length}</b> weak concepts</span></div></div><div class="abx-mode-grid"><button class="primary" onclick="abxDrawMode('algorithm')">Learn Algorithm</button><button onclick="abxDrawMode('rounds')">Case Rounds</button><button onclick="abxDrawMode('loadout')">Antibiotic Loadout</button><button onclick="abxDrawMode('culture')">Culture Callback</button><button class="dark" onclick="abxDrawMode('boss')">Final Boss</button><button onclick="abxDrawRapidReview()">Rapid Review</button></div></section>${abxAlgorithmCard(true)}<article class="card"><h3>Weakness queue</h3>${abxWeaknessRows()}</article><article class="card"><h3>Antibiotic cards</h3><div class="abx-card-grid">${d.antibiotics.map(a=>abxAntibioticCard(a)).join('')}</div></article>`}
function abxAntibioticCard(a){return `<article class="abx-drug-card"><div class="arena-top"><b>${esc(a.name)}</b><span class="tag source">${esc(a.route)}</span></div><p>${(a.coverage||[]).map(c=>c.includes('gram-positive')||c.includes('MRSA')||c.includes('MSSA')?abxGramTag(c):c.includes('gram-negative')||c.includes('Kingella')||c.includes('gonorrhea')||c.includes('Salmonella')?abxGramTag(c):`<span class="source-chip">${esc(c)}</span>`).join(' ')}</p><p><b>Use:</b> ${rich(a.use)}</p><p class="small"><b>Stop/narrow:</b> ${rich(a.stop)}</p></article>`}
function abxDrawMode(mode,d=0){const body=document.getElementById('abxBody');if(!body)return;if(mode==='algorithm')return abxDrawAlgorithmTraining();if(mode==='loadout')return abxDrawLoadout(d);if(mode==='culture')return abxDrawCulture(d);const c=abxCurrentCase(mode,d);body.innerHTML=`<div class="activity-tabs"><button onclick="abxDrawHome()">Home</button><button onclick="abxDrawMode('${mode}',-1)">Previous</button><button onclick="abxDrawMode('${mode}',1)">Next</button><button onclick="abxShowConsult('${mode}','${esc(c.id)}')">ID Consult</button>${mode==='boss'?'<span class="tag urgency">Consult costs 5 points</span>':''}</div>${mode==='boss'?'':abxAlgorithmCard(true)}${abxCaseCard(c,mode)}`;renderStats()}
function abxCaseCard(c,mode){return `<article class="card abx-case"><div class="arena-top"><div><span class="tag">${esc(abxModeLabel(mode))}</span>${abxPathTag(c.classification)}<span class="tag source">Difficulty ${c.difficulty}</span></div><span class="small">${esc(c.id)}</span></div><h3>${rich(c.title)}</h3>${abxCaseFacts(c)}<div id="abxConsult" class="feedback"></div><div class="abx-decision-grid"><section><h3>1. Classify</h3>${abxData().classifications.map(x=>abxChoiceButton('classification',x)).join('')}</section><section><h3>2. Diagnose</h3>${abxDiagnosisChoices(c).map(x=>abxChoiceButton('diagnosis',x)).join('')}</section><section><h3>3. Diagnostic action</h3>${abxActionChoices(c).map(x=>abxChoiceButton('action',x)).join('')}</section></div><section class="abx-tray"><h3>4. Build empiric antibiotic loadout</h3>${abxDropZone('empiric')}<div class="abx-chip-grid">${abxData().antibiotics.map(a=>abxAntibioticChip(a,'empiric')).join('')}</div></section><section class="abx-lab-slip"><div><span class="tag">Culture reveal</span><h3>${rich(c.culture.text)}</h3></div>${abxGramTag(c.culture.gram)}<p class="small">Organism: ${rich(c.culture.organism)}</p></section><section class="abx-tray"><h3>5. Narrow therapy</h3>${abxDropZone('narrow')}<div class="abx-chip-grid">${abxData().antibiotics.map(a=>abxAntibioticChip(a,'narrow')).join('')}</div></section><section><h3>6. Duration</h3><div class="abx-duration-grid">${abxData().durations.map(x=>abxChoiceButton('duration',x)).join('')}</div></section><section><h3>7. Source control</h3>${abxSourceChoices(c).map(x=>abxChoiceButton('sourceControl',x)).join('')}</section><div class="control-row"><button class="primary" onclick="abxSubmitCase('${mode}','${esc(c.id)}')">Submit case</button><button onclick="abxDrawMode('${mode}',1)">Skip</button></div><div id="abxFeedback" class="feedback"></div></article>`}
function abxDiagnosisChoices(c){const base=['Septic arthritis','Osteomyelitis','Acute hematogenous osteomyelitis','Chronic osteomyelitis','Disseminated gonococcal infection','Lyme arthritis','Transient synovitis'];if(!base.includes(c.diagnosis))base.unshift(c.diagnosis);return [...new Set([c.diagnosis,...base])].slice(0,7)}
function abxActionChoices(c){return [...new Set([c.diagnosticAction,...abxData().diagnosticActions])].slice(0,7)}
function abxSourceChoices(c){return [...new Set([c.sourceControl,'Antibiotics only; no source control decision','NSAIDs/rest only','Routine outpatient follow-up only'])].slice(0,4)}
function abxDrawLoadout(d=0){const c=abxCurrentCase('loadout',d),body=document.getElementById('abxBody');body.innerHTML=`<div class="activity-tabs"><button onclick="abxDrawHome()">Home</button><button onclick="abxDrawMode('loadout',-1)">Previous</button><button onclick="abxDrawMode('loadout',1)">Next</button><button onclick="abxShowConsult('loadout','${esc(c.id)}')">ID Consult</button></div>${abxAlgorithmCard(true)}<article class="card abx-case"><span class="tag">Antibiotic Loadout</span>${abxPathTag(c.classification)}<h3>${rich(c.title)}</h3>${abxCaseFacts(c)}<div id="abxConsult" class="feedback"></div><section class="abx-tray"><h3>Build empiric regimen</h3><p class="small">Choose the yellow antibiotic card or cards that cover this risk profile without unnecessary extras.</p>${abxDropZone('empiric')}<div class="abx-chip-grid">${abxData().antibiotics.map(a=>abxAntibioticChip(a,'empiric')).join('')}</div></section><button class="primary" onclick="abxSubmitLoadout('${esc(c.id)}')">Submit loadout</button><div id="abxFeedback" class="feedback"></div></article>`}
function abxDrawCulture(d=0){const c=abxCurrentCase('culture',d),body=document.getElementById('abxBody');body.innerHTML=`<div class="activity-tabs"><button onclick="abxDrawHome()">Home</button><button onclick="abxDrawMode('culture',-1)">Previous</button><button onclick="abxDrawMode('culture',1)">Next</button><button onclick="abxShowConsult('culture','${esc(c.id)}')">ID Consult</button></div>${abxAlgorithmCard(true)}<article class="card abx-case"><span class="tag">Culture Callback</span>${abxPathTag(c.classification)}<h3>${rich(c.title)}</h3><p><b>Initial empiric therapy:</b> ${abxNames(c.empiric)}</p><section class="abx-lab-slip"><h3>${rich(c.culture.text)}</h3>${abxGramTag(c.culture.gram)}<p class="small">Organism: ${rich(c.culture.organism)}</p></section><div id="abxConsult" class="feedback"></div><section class="abx-tray"><h3>Remove unnecessary broad coverage and choose narrowed therapy</h3>${abxDropZone('narrow')}<div class="abx-chip-grid">${abxData().antibiotics.map(a=>abxAntibioticChip(a,'narrow')).join('')}</div></section><section><h3>Duration</h3><div class="abx-duration-grid">${abxData().durations.map(x=>abxChoiceButton('duration',x)).join('')}</div></section><button class="primary" onclick="abxSubmitCulture('${esc(c.id)}')">Submit callback</button><div id="abxFeedback" class="feedback"></div></article>`}
function abxDrawAlgorithmTraining(){const st=abxState(),qs=abxData().algorithmQuestions;const idx=Math.min(st.algorithmStep||0,qs.length-1),q=qs[idx],body=document.getElementById('abxBody');body.innerHTML=`<div class="activity-tabs"><button onclick="abxDrawHome()">Home</button><button onclick="abxDrawMode('rounds')">Case Rounds</button></div>${abxAlgorithmCard()}<article class="card question-box"><div class="arena-top"><div><span class="tag">Algorithm Training</span><h3>${esc(q.title)}</h3></div><span class="counter">${idx+1}/${qs.length}</span></div><p><b>${rich(q.prompt)}</b></p><div>${q.choices.map(x=>`<button class="choice" onclick="abxAnswerAlgorithm('${esc(x)}')">${rich(x)}</button>`).join('')}</div><div id="abxFeedback" class="feedback"></div></article><article class="card"><h3>Unlocked sections</h3><div class="abx-weak-grid">${qs.slice(0,idx).map(x=>`<span class="source-chip">${esc(x.unlock)}</span>`).join('')||'<span class="small">Answer the first prompt to unlock the pathway.</span>'}</div></article>`}
function abxAnswerAlgorithm(choice){const st=abxState(),q=abxData().algorithmQuestions[Math.min(st.algorithmStep||0,abxData().algorithmQuestions.length-1)],ok=choice===q.answer;const f=document.getElementById('abxFeedback');f.classList.add('show');if(ok){st.algorithmStep=Math.min((st.algorithmStep||0)+1,abxData().algorithmQuestions.length);st.score+=5;st.total+=5;complete(`antibiotic:algorithm:${q.title}`,true);f.innerHTML=`<b>Correct.</b> Unlocked: ${esc(q.unlock)}.<br><button onclick="abxDrawMode('algorithm')">Continue</button>`}else{st.total+=5;complete(`antibiotic:algorithm:${q.title}`,false);f.innerHTML=`<b>Not yet.</b> ID Consult: ${rich(q.answer)} is the branch this clue is testing.`}save();renderStats()}
function abxSubmitLoadout(caseId){const c=abxData().cases.find(x=>x.id===caseId),selected=abxSelectedIds('empiric'),ok=abxMatches(selected,c.empiric,c.empiricAlternatives);abxFinish(`antibiotic:loadout:${c.id}`,ok?25:0,25,ok,ok?[]:c.mistakeTags,`<b>${ok?'Correct loadout.':'Coverage gap.'}</b> Target: ${abxNames(c.empiric)}. ${rich(c.feedback)}`,c,'loadout')}
function abxSubmitCulture(caseId){const c=abxData().cases.find(x=>x.id===caseId),narrow=abxSelectedIds('narrow'),duration=abxSelected('duration');let score=0,total=25,tags=[];const narrowOk=abxMatches(narrow,c.narrowing,c.narrowingAlternatives),durationOk=duration===c.duration;if(narrowOk)score+=15;else tags.push('failed_to_narrow');if(durationOk)score+=10;else tags.push('wrong_duration');abxFinish(`antibiotic:culture:${c.id}`,score,total,score>=20,tags,`<b>${score>=20?'Good callback.':'Callback needs repair.'}</b> Narrow to ${abxNames(c.narrowing)}. Duration: ${esc(c.duration)}. ${rich(c.feedback)}`,c,'culture')}
function abxSubmitCase(mode,caseId){const c=abxData().cases.find(x=>x.id===caseId);let score=0,total=0,tags=[];const st=abxState();function add(ok,pts,tag){total+=pts;if(ok)score+=pts;else if(tag)tags.push(tag)}add(abxSelected('classification')===c.classification,5,'wrong_pathway');add(abxSelected('diagnosis')===c.diagnosis,10,'wrong_diagnosis');add(abxSelected('action')===c.diagnosticAction,10,c.classification==='Joint infection'?'failed_to_aspirate':'wrong_diagnostic_action');const emp=abxSelectedIds('empiric');add(abxMatches(emp,c.empiric,c.empiricAlternatives),15,c.mistakeTags[0]);if(c.classification.includes('Mimic'))add(emp.length===0,10,'treated_mimic_with_antibiotics');const narrow=abxSelectedIds('narrow');add(abxMatches(narrow,c.narrowing,c.narrowingAlternatives),15,'failed_to_narrow');add(abxSelected('duration')===c.duration,10,'wrong_duration');add(abxSelected('sourceControl')===c.sourceControl,10,'missed_source_control');if(mode==='boss'&&st.consultCase[c.id])score=Math.max(0,score+abxData().scoring.consultPenalty);abxFinish(`antibiotic:${mode}:${c.id}`,score,total,score/Math.max(1,total)>=.72,tags,abxResultHtml(c,score,total),c,mode)}
function abxResultHtml(c,score,total){return `<b>Score: ${score}/${total}</b><hr><p><b>Diagnosis:</b> ${rich(c.diagnosis)} ${abxPathTag(c.classification)}</p><p><b>Empiric:</b> ${abxNames(c.empiric)}</p><p><b>Narrow:</b> ${abxNames(c.narrowing)}</p><p><b>Duration:</b> ${esc(c.duration)}</p><p><b>Why:</b> ${rich(c.feedback)}</p><p><b>Memory hook:</b> ${rich(c.memoryHook)}</p>`}
function abxFinish(itemId,score,total,ok,tags,html,c,mode){const st=abxState();st.score+=score;st.total+=total;for(const tag of tags.filter(Boolean)){st.weakness[tag]=(st.weakness[tag]||0)+1;if(st.weakness[tag]>=2){const target=abxData().cases.find(x=>x.mistakeTags.includes(tag));if(target&&!st.reviewQueue.includes(target.id))st.reviewQueue.push(target.id)}}st.lastResult={caseId:c.id,score,total,tags};complete(itemId,ok);save();const f=document.getElementById('abxFeedback');if(f){f.classList.add('show');f.innerHTML=`${html}<hr><p><b>ID Consult:</b> ${ok?'Good stewardship. Keep narrowing when cultures simplify the target.':'Review the algorithm branch and watch the coverage meter before submitting.'}</p><button onclick="abxDrawMode('${mode}',1)">Next ${esc(abxModeLabel(mode))}</button><button onclick="abxDrawHome()">Summary</button>`}renderStats()}
function abxShowConsult(mode,caseId){const c=abxData().cases.find(x=>x.id===caseId),st=abxState();st.consultCase[c.id]=true;if(mode==='boss')st.consults++;save();const f=document.getElementById('abxConsult');if(f){f.classList.add('show');f.innerHTML=`<b>ID Consult:</b> You are on the ${rich(c.classification)} pathway. Key loadout: ${abxNames(c.empiric)}. Culture narrowing target: ${abxNames(c.narrowing)}. <button onclick="this.parentElement.classList.remove('show')">Hide</button>`}}
function abxDrawRapidReview(){const d=abxData(),body=document.getElementById('abxBody');body.innerHTML=`<div class="activity-tabs"><button onclick="abxDrawHome()">Home</button><button onclick="abxDrawMode('rounds')">Case Rounds</button></div><article class="card"><span class="tag">Rapid Review</span><h3>Organism to Coverage Map</h3><div class="grid">${d.organisms.map(o=>`<article class="card"><h3>${rich(o.name)}</h3>${abxGramTag(o.gram)}<p>${esc(o.morphology)}</p><p>${(o.coverage||[]).map(x=>`<span class="abx-inline-chip">${esc(abxById(x).name||x)}</span>`).join(' ')}</p></article>`).join('')}</div></article><article class="card"><h3>Antibiotic Cards</h3><div class="abx-card-grid">${d.antibiotics.map(a=>abxAntibioticCard(a)).join('')}</div></article>`}
function abxDropZone(role){return `<div class="abx-drop-zone" data-role="${esc(role)}" ondragover="event.preventDefault()" ondrop="abxDropChip(event,this)"><b>${role==='empiric'?'Treatment tray':'Narrowed therapy tray'}</b><span>Click or drag yellow antibiotic cards here.</span></div>`}
function abxRefreshTray(role){document.querySelectorAll(`.abx-drop-zone[data-role="${CSS.escape(role)}"]`).forEach(zone=>{const names=abxSelectedIds(role).map(id=>abxById(id).name);zone.innerHTML=`<b>${role==='empiric'?'Treatment tray':'Narrowed therapy tray'}</b><span>${names.length?names.join(' + '):'Click or drag yellow antibiotic cards here.'}</span>`})}
window.renderAntibioticCommand=renderAntibioticCommand;window.abxDrawHome=abxDrawHome;window.abxDrawMode=abxDrawMode;window.abxDrawRapidReview=abxDrawRapidReview;window.abxChooseOne=function(btn){btn.parentElement.querySelectorAll(`[data-group="${btn.dataset.group}"]`).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')};window.abxToggleChip=function(btn){btn.classList.toggle('selected');abxRefreshTray(btn.dataset.role)};window.abxDragStart=function(ev){ev.dataTransfer.setData('text/plain',ev.currentTarget.dataset.role+'|'+ev.currentTarget.dataset.id)};window.abxDropChip=function(ev,zone){ev.preventDefault();const [role,id]=String(ev.dataTransfer.getData('text/plain')||'').split('|');if(role!==zone.dataset.role)return;const chip=document.querySelector(`.abx-chip[data-role="${CSS.escape(role)}"][data-id="${CSS.escape(id)}"]`);if(chip&&!chip.classList.contains('selected'))chip.classList.add('selected');abxRefreshTray(role)};window.abxSubmitCase=abxSubmitCase;window.abxSubmitLoadout=abxSubmitLoadout;window.abxSubmitCulture=abxSubmitCulture;window.abxAnswerAlgorithm=abxAnswerAlgorithm;window.abxShowConsult=abxShowConsult;
})();
